import type { KindMap } from "../core/types.ts";
import table from "./kindMap.json";

/**
 * Wikidata class → [kind, English label], generated by scripts/build-kind-map.ts (TS-13).
 * JSON imports widen the tuples to string[], hence the cast; the builder writes only valid kinds.
 */
export const KIND_MAP = table as unknown as KindMap;
